config/routes.rb
Rails.application.routes.draw do
  get 'contact/create'
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      get '/' => 'pages#home'
      # get "/about" => "pages#about"
      # get "/contact" => "pages#contact"

      resources :blogposts, only: [:show]
      
      resources :contacts, only: [:new, :create]


    end
  end

  authenticated :user do
    root 'dashboard#index'

    resources :users do
      resources :blogposts
    end

    resources :users do
      resources :employments
    end

    resources :users do
      resources :portfolios
    end

    resources :users do
      resources :projects
    end

    resources :portfolios

    resources :blogposts

    resources :employments

    resources :projects

    resources :dashboard, only: [:index]


  end
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
    belongs_to :user
    has_rich_text :blog_text
    has_one_attached :photo

    extend FriendlyId
   friendly_id :slug, use: :slugged

   ##...Validations for slug...##
   validates :slug, presence: true # Validates Presence i.e Slug can't be blank.
   validates :slug, uniqueness: true # Validates uniqueness i.e every slug must be unique.
   validates :slug, length: { in: 2..2000 } # Validates length i.e min & max length of the slug. 
   validates :slug, format: { with: /\A[a-zA-Z0-9-_]+\z/,
   message: ":only letters(A-Z or a-z), numbers(0-9), dashes(-) and underscores(_) are allowed" } # Validates format of the slug.

    
end

app/controllers/blogpost_controller.rb
class BlogpostController < ApplicationController

    def index
        @blogposts = Blogpost.all
    end

    def show
        @blogposts = Blogpost.find(params[:id])
    end

    def new
        @blogposts = Blogpost.new
    end

    def create
        @blogposts = Blogpost.new(blogpost_params)
        @blogposts.user = current_user
        if @blogposts.save!
            redirect_to user_blogpost_path(@blogposts)
            else
            render 'new'
        end
    end

    def edit
        @blogposts = Blogpost.find(params[:id])
    end

    def update
        @blogposts = Blogpost.find(params[:id])
        @blogposts.update(blogpost_params)
    # redirect_to blogposts_path(@blogpost)
    end

    def destroy
        @blogposts = Blogpost.find(params[:id])
        @blogposts.destroy
    # redirect_to blogposts_path(@blogpost)
    end

    private

    def blogpost_params
    params.require(:blogposts).permit(:user_id, :blog_title, :blog_sub_heading, :blog_text, :photo)
    end


end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
    before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

    def index
        @blogposts = Blogpost.all
    end

    def show
        @blogpost = Blogpost.friendly.find(params[:id])
    end

    def new
        @blogposts = Blogpost.new
    end

    def create
        @blogposts = Blogpost.new(blogpost_params)
        @blogposts.user = current_user
        if @blogposts.save!
            redirect_to blogpost_path(@blogposts)
            else
            render 'new'
        end
    end

    def edit
        @blogposts = Blogpost.friendly.find(params[:id])
    end

    def update
        @blogposts = Blogpost.friendly.find(params[:id])
        @blogposts.update(blogpost_params)
        redirect_to blogposts_path(@blogposts)
    end

    def destroy
        @blogposts = Blogpost.friendly.find(params[:id])
        @blogposts.destroy
        redirect_to blogposts_path(@blogposts)
    end

    private

    def set_blogpost
        @blogpost = Blogpost.friendly.find(params[:id])
     end

    def blogpost_params
    params.require(:blogpost).permit(:user_id, :blog_title, :blog_sub_heading, :blog_text, :date, :photo, :content, :slug)
    end


end

app/views/blogposts/edit.html.erb
<div class="page-content-area">
<h1>Create a Blogpost</h1>
    <h2>Fill in the details below</h2>
        <%= simple_form_for [@blogposts] do |f| %>
            <%= f.input :blog_title,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Blogpost Title" }%>
            <%= f.input :blog_sub_heading,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Blogpost Sub Heading" }%>
            <%= f.input :slug,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Slug" }%>
            <%= f.input :blog_text,
                        as: :rich_text_area,
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Blog Text" }%>
            <%= f.input :photo,
                        autofocus: true,
                        as: :file %>
            <%= f.input :date, 
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Date" } %>
            <%= f.submit "UPDATE", class: "btn btn-primary" %>
        <% end %>
</div>

app/views/blogposts/index.html.erb
<div class="page-content-area">
    <h1>All Blogposts</h1>
    <p>All Blogposts should appear here</p>
    <div>
        <div class="button-container">
            <%= link_to "Add New", new_user_blogpost_path(current_user), class: "button-main" %>
        </div>
        <div class="table-container">
            <table>
                <th>Blogposts</th>
                <tbody>
                    <tr>
                        <% @blogposts.each do |blogpost| %>
                        <td>
                            <h3 class="table-h1"><%= blogpost.blog_title %></h3>
                            <p class="table-h2"><%= blogpost.blog_sub_heading %></p>
                            <p class="table-p"><%= truncate(strip_tags(blogpost.blog_text.to_s), length: 100) %></p>
                            <div class="flex table-button-spacing">
                                <%= link_to "Edit", edit_blogpost_path(blogpost),class: "td-button" %>
                                <%= link_to "Delete", blogpost_path(blogpost), method: :delete , class: "td-button" %>
                                <%= link_to "View", blogpost_path(blogpost), class: "td-button" %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>    
    </div>
</div>

app/views/blogposts/new.html.erb
<div class="page-content-area">
    <h1>Create a Blogpost</h1>
    <h2>Fill in the details below</h2>
        <%= simple_form_for [@blogposts] do |f| %>
            <%= f.input :blog_title,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Blogpost Title" }%>
            <%= f.input :blog_sub_heading,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Blogpost Sub Heading" }%>
            <%= f.input :slug,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Slug" }%>
            <%= f.input :blog_text,
                        as: :rich_text_area,
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Blog Text" }%>
            <%= f.input :photo,
                        autofocus: true,
                        as: :file  %>
            <%= f.input :date, 
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Date" } %>
            <%= f.submit "CREATE", class: "btn btn-primary" %>
        <% end %>
</div>

app/views/blogposts/show.html.erb
<div class="page-content-area-blog">
    <% content_for :meta_title, "#{@blogpost.blog_title} | #{DEFAULT_META["meta_product_name"]}" %>
    <% content_for :meta_description, @blogpost.blog_sub_heading %>
    <% content_for :meta_image, cl_image_path(@blogpost.photo.key) %>
    <div>      
        <h3 class="table-h1"><%= @blogpost.blog_title %></h3>
        <p class="table-h2"><%= @blogpost.blog_sub_heading %></p>
        <p class="table-h2"><%= @blogpost.date %></p>
        <p class="table-p"><%= @blogpost.blog_text%></p>
        <div class="flex table-button-spacing">
    </div>
    <% if user_signed_in? %>
    <div class="flex table-button-spacing">
        <%= link_to "Back to all blogposts", user_blogposts_path(current_user), class: "td-button" %>
    </div>
    <% else %>
    <div class="flex table-button-spacing">
        <%= link_to "Back", root_path, class: "td-button" %>
    </div>
    <% end%>
</div>