config/routes.rb
Rails.application.routes.draw do
  get 'contact/create'
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      get '/' => 'pages#home'
      # get "/about" => "pages#about"
      # get "/contact" => "pages#contact"

      resources :blogposts, only: [:show]
      
      resources :contacts, only: [:new, :create]


    end
  end

  authenticated :user do
    root 'dashboard#index'

    resources :users do
      resources :blogposts
    end

    resources :users do
      resources :employments
    end

    resources :users do
      resources :portfolios
    end

    resources :users do
      resources :projects
    end

    resources :portfolios

    resources :blogposts

    resources :employments

    resources :projects

    resources :dashboard, only: [:index]


  end
end

app/models/employment.rb
class Employment < ApplicationRecord
  belongs_to :user
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
    def index
        @employments = Employment.all
    end

    def show
        @employments = Employment.find(params[:id])
    end

    def new
        @employments = Employment.new
    end

    def create
        @employments = Employment.new(employment_params)
        @employments.user = current_user
        if @employments.save!
            redirect_to employment_path(@employments)
            else
            render 'new'
        end
    end

    def edit
        @employments = Employment.find(params[:id])
    end

    def update
        @employments = Employment.find(params[:id])
        @employments.update(employment_params)
        redirect_to employments_path(@employments)
    end

    def destroy
        @employments = Employment.find(params[:id])
        @employments.destroy
        redirect_to employments_path(@employments)
    end

    private

    def employment_params
    params.require(:employment).permit(:user_id, :position_title, :company_name, :company_url, :date, :company_description)
    end
end

app/views/employments/edit.html.erb
<div class="page-content-area">
<h1>Edit Project</h1>
    <h2>Fill in the details below</h2>
        <%= simple_form_for [@employments] do |f| %>
            <%= f.input :position_title,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Position Title" }%>
            <%= f.input :company_name,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Company Name" }%>
            <%= f.input :company_url,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Company URL" }%>
            <%= f.input :company_description,
                        :as => :text,
                        required: true,
                        autofocus: true,
                        input_html: { class: '', autocomplete: "Company Description" }%>
            <%= f.input :date, 
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Date" } %>
            <%= f.input :photo,
                        autofocus: true,
                        as: :file %>
            <%= f.submit "UPDATE", class: "btn btn-primary" %>
        <% end %>
</div>

app/views/employments/index.html.erb
<div class="page-content-area">
    <h1>All Employment Posts</h1>
    <p>All past jobs should appear here</p>
    <div>
        <div class="button-container">
            <%= link_to "Add New", new_user_employment_path(current_user), class: "button-main" %>
        </div>
        <div class="table-container">
            <table>
                <th>Past Employment</th>
                <tbody>
                    <tr>
                        <% @employments.each do |employment| %>
                        <td>
                            <h3 class="table-h1"><%= employment.position_title %></h3>
                            <p class="table-h2"><%= employment.company_name %></p>
                            <p class="table-p"><%= employment.company_url %></p>
                            <p class="table-p"><%= employment.company_description %></p>
                            <div class="flex table-button-spacing">
                                <%= link_to "Edit", edit_employment_path(employment),class: "td-button" %>
                                <%= link_to "Delete", employment_path(employment), method: :delete , class: "td-button" %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>    
    </div>
</div>

app/views/employments/new.html.erb
<div class="page-content-area">
<h1>Add to job experience</h1>
    <h2>Fill in the details below</h2>
        <%= simple_form_for [@employments] do |f| %>
            <%= f.input :position_title,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Position Title" }%>
            <%= f.input :company_name,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Company Name" }%>
            <%= f.input :company_url,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Company URL" }%>
            <%= f.input :company_description,
                        :as => :text,
                        required: true,
                        autofocus: true,
                        input_html: { class: '', autocomplete: "Company Description" }%>
            <%= f.input :date, 
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Date" } %>
            <%= f.input :photo,
                        autofocus: true,
                        as: :file %>
            <%= f.submit "CREATE", class: "btn btn-primary" %>
        <% end %>
</div>

app/views/employments/show.html.erb
<div class="page-content-area">      
    <h3 class="table-h1"><%= @employments.position_title %></h3>
    <p class="table-h2"><%= @employments.company_name %></p>
    <p class="table-p"><%= @employments.company_url %></p>
    <p class="table-p"><%= @employments.company_description %></p>
</div>