config/routes.rb
Rails.application.routes.draw do
  get 'contact/create'
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      get '/' => 'pages#home'
      # get "/about" => "pages#about"
      # get "/contact" => "pages#contact"

      resources :blogposts, only: [:show]
      
      resources :contacts, only: [:new, :create]


    end
  end

  authenticated :user do
    root 'dashboard#index'

    resources :users do
      resources :blogposts
    end

    resources :users do
      resources :employments
    end

    resources :users do
      resources :portfolios
    end

    resources :users do
      resources :projects
    end

    resources :portfolios

    resources :blogposts

    resources :employments

    resources :projects

    resources :dashboard, only: [:index]


  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "IZ", root_path,class:"navbar-brand nav-logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag ("iz-avatar.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About Me", "#aboutme" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Employment", "#Employment" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Portfolio", "#Portfolio" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blogposts", "#Blogposts" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Languages", "#Languages" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Programs", "#Programs" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Education", "#Education" , class: "nav-link nav-hover" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", "#Contact",  class: "nav-link nav-hover" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_vertnav.html.erb
<% if user_signed_in? %>
<div class="vertnav-bar">
    <div class="">
        <%= link_to "Dashboard", dashboard_index_path(current_user) , class:"navitem"%>
    </div>
    <div class="navitem">
        <%= link_to "Blogposts", user_blogposts_path(current_user), class:"navitem"%>
    </div>
    <div class="navitem">
        <%= link_to "Employment", user_employments_path(current_user), class:"navitem"%>
    </div>
    <div class="navitem">
        <%= link_to "Portfolio", user_portfolios_path(current_user), class:"navitem"%>
    </div>
    <div class="navitem">
        <%= link_to "Projects", user_projects_path(current_user) , class:"navitem"%>
    </div>
    <% end %>
</div>