config/routes.rb
Rails.application.routes.draw do
  get 'contact/create'
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      get '/' => 'pages#home'
      # get "/about" => "pages#about"
      # get "/contact" => "pages#contact"

      resources :blogposts, only: [:show]
      
      resources :contacts, only: [:new, :create]


    end
  end

  authenticated :user do
    root 'dashboard#index'

    resources :users do
      resources :blogposts
    end

    resources :users do
      resources :employments
    end

    resources :users do
      resources :portfolios
    end

    resources :users do
      resources :projects
    end

    resources :portfolios

    resources :blogposts

    resources :employments

    resources :projects

    resources :dashboard, only: [:index]


  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index
        @projects = Project.all
    end

    def show
        @projects = Project.find(params[:id])
    end

    def new
        @projects = Project.new
    end

    def create
        @projects = Project.new(project_params)
        @projects.user = current_user
        if @projects.save!
            redirect_to project_path(@projects)
            else
            render 'new'
        end
    end

    def edit
        @projects = Project.find(params[:id])
    end

    def update
        @projects = Project.find(params[:id])
        @projects.update(project_params)
        redirect_to user_projects_path(@projects)
    end

    def destroy
        @projects = Project.find(params[:id])
        @projects.destroy
        redirect_to user_projects_path(@projects)
    end

    private

    def project_params
    params.require(:project).permit(:user_id, :project_name, :project_url, :date, :project_description )
    end
end

app/views/projects/edit.html.erb
<div class="page-content-area">
<h1>Edit a project</h1>
    <h2>Fill in the details below</h2>
        <%= simple_form_for [@projects] do |f| %>
            <%= f.input :project_name,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Project Name" }%>
            <%= f.input :project_url,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Project URL" }%>
            <%= f.input :project_description,
                        :as => :text,
                        required: true,
                        autofocus: true,
                        input_html: { class: '', autocomplete: "Project Description" }%>
            <%= f.input :photo,
                        autofocus: true,
                        as: :file %>
            <%= f.input :date, 
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Date" } %>
            <%= f.submit "CREATE", class: "btn btn-primary" %>
        <% end %>
</div>

app/views/projects/index.html.erb
<div class="page-content-area">
    <h1>All Projects</h1>
    <p>All Projects should appear here</p>
    <div>
        <div class="button-container">
            <%= link_to "Add New", new_user_project_path(current_user), class: "button-main" %>
        </div>
        <div class="table-container">
            <table>
                <th>Projects</th>
                <tbody>
                    <tr>
                        <% @projects.each do |project| %>
                        <td>
                            <h3 class="table-h1"><%= project.project_name %></h3>
                            <p class="table-h2"><%= project.project_url %></p>
                            <p class="table-p"><%= project.project_description %></p>
                            <div class="flex table-button-spacing">
                                <%= link_to "Edit", edit_project_path(project),class: "td-button" %>
                                <%= link_to "Delete", project_path(project), method: :delete , class: "td-button" %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>    
    </div>
</div>

app/views/projects/new.html.erb
<div class="page-content-area">
<h1>Create a Blogpost</h1>
    <h2>Fill in the details below</h2>
        <%= simple_form_for [@projects] do |f| %>
            <%= f.input :project_name,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Project Name" }%>
            <%= f.input :project_url,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "Project URL" }%>
            <%= f.input :project_description,
                        :as => :text,
                        required: true,
                        autofocus: true,
                        input_html: { class: '', autocomplete: "Project Description" }%>
            <%= f.input :photo,
                        autofocus: true,
                        as: :file %>
            <%= f.input :date, 
                        required: true,
                        autofocus: true,
                        input_html: { class: "text-area-blog", autocomplete: "Date" } %>
            <%= f.submit "CREATE", class: "btn btn-primary" %>
        <% end %>
</div>

app/views/projects/show.html.erb
<div class="page-content-area">      
    <h3 class="table-h1"><%= @projects.project_name %></h3>
    <p class="table-h2"><%= @projects.project_url %></p>
    <p class="table-p"><%= @projects.project_description %></p>
    <div class="flex table-button-spacing">
</div>